### ISSUE TITLE
Upgrade base source to 5.3.1

### ISSUE THREAD

**Issue by kageiit** [facebook/proguard#11]
ProGuard 5.3.1 is available now. This update implements a performance improvement for recent JREs. More specifically, it avoids extensive use of String#substring, which nowadays copies the underlying char[] array instead of sharing it, thus causing a lot of churn for the garbage collector

**Comment by alsutton** [comment]
Thanks for the letting us know. Commit dac342043e2e12ab842bd70dc954a77a81720225 has been updates the base revision to 5.3.1.
