### ISSUE TITLE
fb/proguard seems worse than vanilla

### ISSUE THREAD

**Issue by kageiit** [facebook/proguard#12]
Ran this fork on an android project to compare proguard run time and apk size using the exact same code and proguard rules

Vanilla 5.3.1 - 1m25.93s, 3680 kb
fb/proguard based off 5.3.1 - 1m28.98s, 3696 kb

Do you have any benchmarks to claim this fork is actually better? Seems like the latest vanilla version of proguard is actually superior, but I may not have some data that you may be using to still keep this fork alive. Would be great to understand that :)

**Comment by alsutton** [comment]
We use it on our internal apps and we've seen the opposite. Can you share the code you ran your tests on?

**Comment by kageiit** [comment]
You can run the example that ships with proguard itself

Fb Fork
```
time java -jar lib/proguard.jar @examples/proguard.pro
ProGuard, version 5.3.1
Reading program jar [/Users/kage/src/proguard/lib/proguard.jar] (filtered)
Reading library jar [/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/rt.jar]
Preparing output jar [/Users/kage/src/proguard/examples/proguard_out.jar]
  Copying resources from program jar [/Users/kage/src/proguard/lib/proguard.jar] (filtered)

real	0m8.511s
user	0m23.466s
sys	0m0.603s
```

Vanilla 5.3.1
```
time java -jar lib/proguard.jar @examples/proguard.pro
ProGuard, version 5.3.1
Reading program jar [/Users/kage/src/proguard-code/lib/proguard.jar] (filtered)
Reading library jar [/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/rt.jar]
Preparing output jar [/Users/kage/src/proguard-code/examples/proguard_out.jar]
  Copying resources from program jar [/Users/kage/src/proguard-code/lib/proguard.jar] (filtered)

real	0m8.224s
user	0m23.356s
sys	0m0.633s
```

**Comment by kageiit** [comment]
I also ran a test on this opensource project
https://github.com/uber/okbuck

command to run
`./buckw build another-appRelease`

and then switched out the custom proguard jar from `tooling/proguard.jar` to vanilla 5.3.1 and this fork after to check the results. Looking at the buck build trace files gives me these data

Vanilla 5.3.1
<img width="856" alt="screen shot 2016-10-27 at 11 47 08 pm" src="https://cloud.githubusercontent.com/assets/291148/19797445/ea07d9d8-9c9f-11e6-92bb-b6c3ec3e80d1.png">

This fork
<img width="988" alt="screen shot 2016-10-27 at 11 47 19 pm" src="https://cloud.githubusercontent.com/assets/291148/19797449/f2ef8c62-9c9f-11e6-8529-a910eb2a1fef.png">

**Comment by kageiit** [comment]
I think you should test vanilla proguard 5.3.1 on your internal apps to check if this fork is still useful to maintain

**Comment by alsutton** [comment]
I'm still seeing some performance gains here, but from your experiments it looks like they may not be universal on all machines types, so I've asked for the "faster" bit to be removed from the description.

Another benchmark you might want to run is memory usage. It's an area we also see improved in the fork, and it should be independent of machine architecture and hardware configuration.

**Comment by alsutton** [comment]
Just for comparison, here's what I see on my local machine running your test;

```
alsutton-mbp:proguard alsutton$ time java -jar lib/proguard.jar @examples/proguard.pro
ProGuard, version 5.3.1
Reading program jar [/Users/alsutton/Projects/proguard/lib/proguard.jar] (filtered)
Reading library jar [/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/rt.jar]
Preparing output jar [/Users/alsutton/Projects/proguard/examples/proguard_out.jar]
  Copying resources from program jar [/Users/alsutton/Projects/proguard/lib/proguard.jar] (filtered)

real	0m13.505s
user	0m30.435s
sys	0m0.846s
```

```
alsutton-mbp:fb-proguard alsutton$ rm examples/proguard_out.jar ; time java -jar lib/proguard.jar @examples/proguard.pro
ProGuard, version 5.3.1
Reading program jar [/Users/alsutton/Projects/fb-proguard/lib/proguard.jar] (filtered)
Reading library jar [/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/rt.jar]
Preparing output jar [/Users/alsutton/Projects/fb-proguard/examples/proguard_out.jar]
  Copying resources from program jar [/Users/alsutton/Projects/fb-proguard/lib/proguard.jar] (filtered)

real	0m13.303s
user	0m30.040s
sys	0m0.782s

```

**Comment by alsutton** [comment]
"faster" has been removed from the description.

**Comment by kageiit** [comment]
what is "different" on your machine exactly? would be nice if we can get those speed benefits if it requires us to tweak our machines somehow

**Comment by kageiit** [comment]
I am also curious why the changes in the fork cannot be contributed upstream to proguard

**Comment by alsutton** [comment]
I'm not sure how valuable it'll be digging into hardware and OS components. I'm grateful for you highlighting that you have a configuration where it's not as fast, but I'm not sure a recommended hardware spec for the perf improvements would go down well with many people :).

DexGuard (authors or Proguard) are aware of this fork, but I don't know the reason they have for not taking the patches into the mainstream version.
