### ISSUE TITLE
How can I solve this problem,please?

### ISSUE THREAD

**Issue by camilesing** [facebook/proguard#13]
```
Warning: my_class$9$1: can't find referenced method 'java.lang.String access$900()' in program class my_class
```

 I am searching for a long time on net. But no use. Please help or try to give some ideas how to achieve this

Thanks in advance

**Comment by alsutton** [comment]
Can you confirm this only happens on the fb fork of proguard. If this is a problem with proguard in general you should report the issue through their issue tracker at https://sourceforge.net/p/proguard/bugs/

**Comment by alsutton** [comment]
Closing out because there's hasn't been any confirmation this is specifically related to our fork.
