### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by NikosPapakonstantinou** [facebook/proguard#15]
Hello there,

i have installed the package on my vs2015 and i created an apk file but it looks the same.

Do you know how to use it please?I am using devextreme phonegap.

**Comment by alsutton** [comment]
The output of this project is a proguard.jar which can be used as a replacement for the equivalent version of proguard. If you're looking for help on how to use proguard please see the upstream projects documentation which is available from https://www.guardsquare.com/en/proguard
