### ISSUE TITLE
Proguard error

### ISSUE THREAD

**Issue by SamihElsakhawi** [facebook/proguard#18]
I'm using xamarin for android, and I wanted to build my app with proguard.

after I installed it and build my app, I always have this error:

Error Unable to access jarfile C:\Users\samih pc\Documents\Visual Studio 
2015\Projects\App Name
\packages\name.atsushieno.proguard.facebook.5.3.2.2\build\..lib\proguard.jar    
App Name    C:\Users\samih pc\Documents\Visual Studio 
2015\Projects\App Name\App Name\PROGUARD        
I search online and I use the mklink /j , but I still got this error no matter what.

How can i fix that?

Do i need to change the proguard path to with the path of the mklink?

Thanks a lot.

Regards, Sam.

**Comment by alsutton** [comment]
Hi Sam,

This is a fork of proguard with a few modifications. The main prograud site is at https://www.guardsquare.com/en/proguard which contains links to how you can get support for using proguard.
