### ISSUE TITLE
On publishing to jcenter or maven

### ISSUE THREAD

**Issue by cdancy** [facebook/proguard#19]
Any thoughts on publishing this to jcenter or maven? It would be really great if the output, that being the proguard.jar file, were publicly resolvable to be used in build-scripts/plugins/etc. I know they provide it through sourceforce, and I could probably hack together something something to make that resolvable, but it would be much cleaner if we had it in the "proper" place.

Thoughts?

**Comment by cdancy** [comment]
If you're up for publishing to jcenter I could send in a PR to wire this up for you guys. I do this in my own projects with ease. Example can be found here: https://github.com/cdancy/bitbucket-rest/blob/master/gradle/publishing.gradle

**Comment by alsutton** [comment]
Given that it's only a small number of changes my preference would be to push for these changes to be taken up-steam and keep the focus on the authoritative source. The benefits from this fork tend to be limited to large projects, so I'd be reluctant to make it available when most people may not see benefits.

**Comment by cdancy** [comment]
@alsutton fair enough but man ... who is still using sourceforce these days? :)
