### ISSUE TITLE
Upgrading to 4.12 to avoid bug

### ISSUE THREAD

**Issue by blundell** [facebook/proguard#3]
How come you forked at 4.11 and is their a possibility of moving to 4.12 or 5.0?

I ask because of a serious bug with Proguard & Android (when using Google Play Services) that affects 4.11 & is fixed in 4.12.

http://sourceforge.net/p/proguard/bugs/505/

> In any android project with the 'Google Play Service' library to use AdMob or any other,
Proguard 4.11 spit out below error. 4.10 is ok with same proguard script.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by alsutton** [comment]
We've now moved to 5.2.1, so I'm closing the issue. Thanks for reporting it.
