### ISSUE TITLE
What is proguard.jar path?

### ISSUE THREAD

**Issue by RomainPiel** [facebook/proguard#4]
This might not be the correct place to ask that question but I'm going to try. I'd like to use facebook cersion of proguard but I can't find out which one my ide is using. I found one in my android sdk tools/proguard/lib/proguard.jar but removing it doesn't change anything. I'm using Android studio, does it use another version of proguard.jar?

**Comment by laurencedawson** [comment]
Anyone had any further luck integrating into Android Studio?

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by alsutton** [comment]
Closing this issue due to the information from Xavier Ducrohet about proguard being pulled by maven and so not locally overridable.

**Comment by niedzielski** [comment]
@alsutton, how does one use Facebook ProGuard in a Gradle project then?

**Comment by alsutton** [comment]
That's a question you'd need to ask the Gradle team. You can build a jar from this fork, but integration with specific build systems is something best discussed with the group who created the build system.

**Comment by niedzielski** [comment]
@alsutton, that's too bad. I think this project is likely to fall into disuse if it doesn't provide a concise way to use the tool with _the canonical_ Android build system. I appreciate the effort to tend all these open issues (some, a year plus old with no human activity) but it feels like the resolution is wontfix for many of them which doesn't encourage contribution or usage (and certainly not reporting new issues). I'll follow up if I figure something out but it's a little discouraging to read this.
