### ISSUE TITLE
the generated jar could not be scanned by class loader 

### ISSUE THREAD

**Issue by Jaware** [facebook/proguard#5]
the generated jar could not be scanned by class loader 
i tried to use this proguard  ，the generated jar is almost the same to the original jar after decompilation, however the classes in jar could not be scanned by class loader ，i use spring,the sourse code is PathMatchingResourcePatternResolver.java---getClassLoader().getResources("org/demo/config/").
the getResourses method return no jar囧,while when i replace it to the original jar it returned the jar, so strange........can anyone help me...

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by alsutton** [comment]
This issue is now out of date due to this fork being rebased on 5.2.1. Please re-open if you're experiencing the same issues with the latest code.
