### ISSUE TITLE
Unable to find method proguard.KeepClassSpecification

### ISSUE THREAD

**Issue by amc6** [facebook/proguard#8]
After upgrading to Android Studio 1.0, Gradle 2.12, and the gradle plugin 1.0.0, our build is failing with the following error: https://www.dropbox.com/s/c5hjt4swp9h6asx/Screenshot%202014-12-23%2015.57.49.png?dl=0

This is fixes by removing the "classpath ':proguard:' line from our top level build.gradle, but this means that we would be using the official version of proguard and not facebook's fork. I've copied our top level build.gradle below:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        flatDir dirs: 'tools/localMavenRepo/' // for using a local version of proguard
        mavenCentral()
    }
    dependencies {
        classpath ':proguard:' // for using a local version of proguard
        classpath 'com.android.tools.build:gradle:1.0.0'
    }
}
```

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by alsutton** [comment]
Can you re-try with the latest versions of the fork and the tools and report back if this is still an issue.

**Comment by alsutton** [comment]
Closing due to no report of it being an issue after the 5.2.1 rebase.
